Evaluacion360/Evaluacion360/Models/ViewModels/AutoEvaluationQuestionViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

// Auto Evaluacion Preguntas

namespace Evaluacion360.Models.ViewModels
{
    public class AutoEvaluationQuestionViewModel
    {
        [Required]
        public int Numero_Evaluacion { get; set; }
        //public string NombreEvaluacion { get; set; }

        [Required]
        public int Codigo_Proceso { get; set; }
        public string NombreProceso { get; set; }

        [Required]
        public string Codigo_Usuario { get; set; }
        public string NombreUsuario { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public Nullable<DateTime> Fecha { get; set; }

        public string Logros { get; set; }

        public string Metas { get; set; }

        public string Estado_AE { get; set; }
        public string StateDescription { get; set; }

        public Nullable<decimal> Nota_Final_AE { get; set; }

        public string Codigo_Seccion { get; set; }

        public int Numero_Pregunta { get; set; }
        public string TextoPregunta { get; set; }

        public decimal Nota { get; set; }

    }

    public class AutoEvaluationQuestionEditViewModel
    {
        public int Numero_Evaluacion { get; set; }
        public int Codigo_Proceso { get; set; }
        public string NombreProceso { get; set; }
        public string Codigo_Seccion { get; set; }
        public int Numero_Pregunta { get; set; }
        public string TextoPregunta { get; set; }
        public decimal Nota { get; set; }
        public string Codigo_Usuario { get; set; }
        public string NombreUsuario { get; set; }
        public string Logros { get; set; }
        public string Metas { get; set; }
    }

    public class AutoEvaluationQuestionListModel
    {
        public int Numero_Evaluacion { get; set; }
        public string Codigo_Proceso { get; set; }
        public string Codigo_Seccion { get; set; }
        public int Numero_Pregunta { get; set; }
        public decimal Nota { get; set; }
        public string Estado_AE { get; set; }
    }

    public class AutoEvQuestionScoreViewModel
    {
        public string Codigo_Seccion { get; set; }
        public int Numero_Pregunta { get; set; }
        public string Texto_Pregunta { get; set; }
        public decimal Nota { get; set; }
    }

    public class CreateAutoEvaluationQuestionViewModel
    {
        public int Numero_Evaluacion { get; set; }

        public int Codigo_Proceso { get; set; }

        public string Codigo_Usuario { get; set; }

        public Nullable<DateTime> Fecha { get; set; }

        public string Logros { get; set; }

        public string Metas { get; set; }

        public string Estado_AE { get; set; }

        public Nullable<decimal> Nota_Final_AE { get; set; }

        public string Codigo_Seccion { get; set; }

        public int Numero_Pregunta { get; set; }

        public decimal Nota { get; set; }

    }
}

Evaluacion360/Evaluacion360/Controllers/AutoEvaluationQuestionController.cs
using Evaluacion360.Filters;
using Evaluacion360.Models;
using Evaluacion360.Models.ViewModels;
using Evaluacion360.Utils;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Evaluacion360.Controllers
{
    public class AutoEvaluationQuestionController : Controller
    {
        string Mensaje;
        // GET: EvaluacionPreguntas
        [AuthorizeUser(IdOperacion: 5)]
        public ActionResult List(int pagina = 1)
        {
            ActionResult result = null;
            int CantidadRegitrosPorPagina = 0;
            CantidadRegitrosPorPagina = 10;
            try
            {
                Usuarios tUser = (Usuarios)Session["User"];
                var oEvQuestion = new List<AutoEvaluationQuestionListModel>();
                using BD_EvaluacionEntities Db = new BD_EvaluacionEntities();

                oEvQuestion = (from EvQ in Db.Auto_Evaluacion_Preguntas
                               join proc in Db.Procesos_Evaluacion on EvQ.Codigo_Proceso equals proc.Codigo_Proceso
                               join secc in Db.Secciones on EvQ.Codigo_seccion equals secc.Codigo_Seccion
                               join ranq in Db.Preguntas_Aleatorias on EvQ.Codigo_seccion equals ranq.Codigo_Seccion

                               where EvQ.Numero_Pregunta == ranq.Numero_Pregunta
                               orderby EvQ.Codigo_Proceso, EvQ.Codigo_seccion, EvQ.Numero_Pregunta
                               select new AutoEvaluationQuestionListModel
                               {
                                   Numero_Evaluacion = EvQ.Numero_Evaluacion,
                                   Codigo_Proceso = EvQ.Codigo_Proceso.ToString(),
                                   Codigo_Seccion = EvQ.Codigo_seccion,
                                   Numero_Pregunta = EvQ.Numero_Pregunta,
                                   Nota = EvQ.Nota
                               }).ToList();

                var TotalRegistros = oEvQuestion.Count();
                List<AutoEvaluationQuestionListModel> lista = oEvQuestion.Skip((pagina - 1) * CantidadRegitrosPorPagina).Take(CantidadRegitrosPorPagina).ToList();
                var Modelo = new ListAEQViewModel
                {
                    Secciones = lista,
                    PaginaActual = pagina,
                    TotalDeRegistros = TotalRegistros,
                    RegistrosPorPagina = CantidadRegitrosPorPagina
                };
                return View(Modelo);
            }
            catch (Exception exc)
            {
                Mensaje = exc.Message;
                result = new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
                return result;
            }

        }

        // GET: EvaluacionPreguntas/Details/5
        [AuthorizeUser(IdOperacion: 5)]
        public ActionResult Details(AutoEvaluationQuestionViewModel AEQ)
        {
            ViewBag.Procesos = new SelectList(Tools.LeerProcesos(), "Codigo_Proceso", "Nombre_Proceso", "");
            ViewBag.Sections = new SelectList(Tools.LeerSecciones(), "Codigo_Seccion", "Nombre_Seccion", "");
            ViewBag.EvState = new SelectList(Tools.EstadosEvaluaciones(), "IdState", "StateDescription", "");
            try
            {
                //Usuarios tUser = (Usuarios)Session["User"];
                using BD_EvaluacionEntities Db = new BD_EvaluacionEntities();

                Auto_Evaluacion_Preguntas oAeq = Db.Auto_Evaluacion_Preguntas.Find(AEQ.Numero_Evaluacion, AEQ.Codigo_Proceso, AEQ.Codigo_Seccion, AEQ.Numero_Pregunta);
                oAeq.Numero_Evaluacion = AEQ.Numero_Evaluacion;
                oAeq.Codigo_Proceso = AEQ.Codigo_Proceso;
                oAeq.Codigo_seccion = AEQ.Codigo_Seccion.ToString();
                oAeq.Numero_Pregunta = AEQ.Numero_Pregunta;
                oAeq.Nota = AEQ.Nota;
                Mensaje = "Ok";
                return View(new { oAeq, Mensaje });
            }

            catch (Exception ex)
            {
                Mensaje = ex.Message;
            }
            return View(new { Mensaje });
        }

        // GET: EvaluacionPreguntas/Create
        [AuthorizeUser(IdOperacion: 5)]
        public ActionResult Create(string mensaje)
        {
            ViewBag.Status = true;
            Usuarios oUser = (Usuarios)Session["User"];

            ViewBag.Users = new SelectList(Tools.LeerUsuarios(oUser.Codigo_Usuario), "Codigo_Usuario", "Nombre_Usuario", 1);
            ViewBag.Procesos = new SelectList(Tools.LeerProcesos(), "Codigo_Proceso", "Nombre_Proceso", "");
            ViewBag.EvState = new SelectList(Tools.EstadosEvaluaciones(), "IdState", "StateDescription", "");
            ViewBag.Sections = new SelectList(Tools.DominiosPorUsuario(oUser.Codigo_Usuario), "Codigo_Seccion", "Nombre_Seccion");


            if (mensaje != null && mensaje != "")
            {
                if (mensaje == "Ok")
                {
                    ViewBag.Message = "Auto Evaluación Actualizada exitosamente";
                    ViewBag.Status = true;
                }
                else if (mensaje != "Ok")
                {
                    ViewBag.Message = mensaje;
                    ViewBag.Status = false;
                }
            }
            try
            {
                var oAE = new AutoEvaluationQuestionViewModel();
                using BD_EvaluacionEntities Db = new BD_EvaluacionEntities();
                oAE = (from pev in Db.Procesos_Evaluacion
                       join aev in Db.Auto_Evaluaciones on pev.Codigo_Proceso equals aev.Codigo_Proceso
                       join usu in Db.Usuarios on aev.Codigo_Usuario equals usu.Codigo_Usuario
                       join eev in Db.Estado_Evaluaciones on aev.Estado_AE equals eev.IdState
                       where usu.Codigo_Usuario == oUser.Codigo_Usuario && aev.Estado_AE == "A" 
                       orderby pev.Nombre_Proceso
                       select new AutoEvaluationQuestionViewModel
                       {
                           Numero_Evaluacion = aev.Numero_Evaluacion,
                           Codigo_Proceso = pev.Codigo_Proceso,
                           NombreProceso = pev.Nombre_Proceso,
                           Codigo_Usuario = aev.Codigo_Usuario,
                           NombreUsuario = usu.Nombre_Usuario,
                           Fecha = aev.Fecha,
                           Logros = aev.Logros ?? "",
                           Metas = aev.Metas ?? "",
                           Estado_AE = aev.Estado_AE ?? "",
                           StateDescription = eev.StateDescription ?? "",
                           Nota_Final_AE = aev.Nota_Final_AE ?? 0,
                           Codigo_Seccion = "",
                           Numero_Pregunta = 0,
                           TextoPregunta = "",
                           Nota = oAE.Nota,
                       }).FirstOrDefault();
                if (oAE == null)
                {
                    ViewBag.Message = "Todas las preguntas de Auto Evaluación ya fueron respondidas";
                    ViewBag.Status = false;
                }
                return View(oAE);
            }
            catch (Exception ex)
            {
                mensaje = ex.Message;
                return View(mensaje);
            }

        }

        // POST: EvaluacionPreguntas/Create
        [AuthorizeUser(IdOperacion: 5)]
        [HttpPost]
        public ActionResult Create(AutoEvaluationQuestionViewModel ae)
        {
            ViewBag.Status = true;
            ViewBag.SectionState = new SelectList(Tools.LeerEstados(), "IdState", "StateDescription", "");
            ViewBag.Sections = new SelectList(Tools.LeerSecciones(), "Codigo_Seccion", "Nombre_Seccion", "");
            ViewBag.Procesos = new SelectList(Tools.LeerProcesos(), "Codigo_Proceso", "Nombre_Proceso", "");
            ViewBag.EvState = new SelectList(Tools.EstadosEvaluaciones(), "IdState", "StateDescription", "");
            // TODO: Add insert logic here
            try
            {
                //Validación del Modelo
                if (ModelState.IsValid)
                {
                    #region Graba Datos
                    using var bd = new BD_EvaluacionEntities();
                    var oAe = new Auto_Evaluacion_Preguntas
                    {
                        Numero_Evaluacion = ae.Numero_Evaluacion,
                        Codigo_Proceso = ae.Codigo_Proceso,
                        Codigo_seccion = ae.Codigo_Seccion,
                        Numero_Pregunta = ae.Numero_Pregunta,
                        Nota = ae.Nota,
                    };
                    bd.Auto_Evaluacion_Preguntas.Add(oAe);
                    bd.SaveChanges();

                    Mensaje = "Ok";
                    #endregion
                }
                else
                {
                    string errors = string.Empty;
                    foreach (var item in ModelState.Values)
                    {
                        if (item.Errors.Count > 0)
                        {
                            Mensaje += string.Format("{0} \n", item.Errors[0].ErrorMessage);
                        }
                        Mensaje += " Contacte al Administrador";
                    }
                }
            }
            catch (Exception e)
            {
                Mensaje = "Ocurrió el siguiente error " +
                          e.InnerException.InnerException.Message +
                          " Contacte al Administrador";
            }
            return Json(data: new { error = true, data = Mensaje }, JsonRequestBehavior.AllowGet);
        }

        // GET: EvaluacionPreguntas/Edit/5
        [AuthorizeUser(IdOperacion: 5)]

Evaluacion360/Evaluacion360/Views/AutoEvaluationQuestion/Create.cshtml
@model Evaluacion360.Models.ViewModels.AutoEvaluationQuestionViewModel

@{
    ViewBag.Title = "Preguntas Auto Evaluación";
    Layout = ""; ;
}

<!DOCTYPE html>

<html lang="es">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Preguntas Auto Evaluación</title>
    <!-- meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Pooled Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript">

        addEventListener("load", function()
            { setTimeout(hideURLbar, 0); },
            false);
            function hideURLbar()
            { window.scrollTo(0,1); }

        window.setTimeout(function () {
            $(".alert-success").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
            }); }, 3000);

        window.setTimeout(function () {
            $(".alert-danger").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
            }); }, 5000);
    </script>

    <!-- tables -->
    <link rel="stylesheet" type="text/css" href="~/Css/table-style.css" />
    <link rel="stylesheet" type="text/css" href="~/Css/basictable.css" />
    <!-- //tables -->

    <!-- Bootstrap Core CSS -->
    <link href="~/Css-Pool/bootstrap.min.css" rel="stylesheet" type='text/css' />

    <!-- Custom CSS -->
    <link href="~/Css-Pool/style2.css" rel='stylesheet' type='text/css' />
    <link href="~/Css-Modernizer/style.css" rel="stylesheet" />

    <!-- Graph CSS -->
    <link href="~/Css-Pool/font-awesome.css" rel="stylesheet" />
    <link href="~/Css/jquery-ui.css" rel="stylesheet" />

    <!-- jQuery -->
    <script src="~/js/jquery-2.1.4.min.js"></script>
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
    <!-- //jQuery -->

    <link href='//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400' rel='stylesheet' type='text/css' />
    <link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css' />

    <!-- lined-icons -->
    <link href="~/Css/icon-font.min.css" rel="stylesheet" type='text/css' />
    <!-- //lined-icons -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    @if (ViewBag.Message != null)
    {
        if (ViewBag.Status)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong style="font-size:medium">@ViewBag.Message</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }

        else
        {
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong style="font-size:medium">@ViewBag.Message</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
    }
    <div id="mensaje">

    </div>

    <div class="panel-body" , style="background-color:#fff">
        <div class="notification_header" style="text-align:center">
            <h1 class="center-block">Responder Auto Evaluación</h1>
        </div>
        <br />

        <form form="role" class="form-horizontal" action="Create" method="post" id="formAEQ" , name="formAEQ">
            @Html.AntiForgeryToken()

            <input type="hidden" id="urlGet" name="urlGet" value="/AutoEvaluationQuestion/GetQuestionByUser" />
            <input type="hidden" id="urlPost" name="urlPost" value="/AutoEvaluationQuestion/Edit" />

            <div class="form-group has-feedback">
                <label class="col-md-3 control-label ">Proceso</label>
                <div class="col-md-8">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-puzzle-piece"></i></span>
                        @Html.HiddenFor(model => model.Codigo_Proceso, new { @id = "codProc" })
                        @Html.EditorFor(model => model.NombreProceso, new { htmlAttributes = new { id = "nomProc", @readonly = "readonly", type = "text", @class = "form-control1", @placeholder = "Proceso", @required = "required", autofocus = "autofocus" } })
                    </div>
                </div>
            </div>

            <div class="form-group has-feedback">
                <label class="col-md-3 control-label ">Nro Evaluación</label>
                <div class="col-md-8">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-hashtag"></i></span>
                        @Html.EditorFor(model => model.Numero_Evaluacion, new { htmlAttributes = new { @id = "numEval", @readonly = "readonly", type = "text", @class = "form-control1", @placeholder = "Nro. de Evaluación", @required = "required" } })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-3 control-label">Usuario</label>
                <div class="col-md-8">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        @Html.HiddenFor(model => model.Codigo_Usuario, new { id = "codUser" })
                        @Html.EditorFor(model => model.NombreUsuario, new { htmlAttributes = new { id = "nomUser", @readonly = "readonly", type = "text", @class = "form-control1", @placeholder = "Nro. de Evaluación", @required = "required" } })
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group has-feedback">
                <label class="col-md-3 control-label ">Metas</label>
                <div class="col-md-8">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-tasks"></i></span>
                        @Html.EditorFor(model => model.Metas, new { htmlAttributes = new { id = "metas", @required = "required", type = "text", minlength = 6, @class = "form-control1", @placeholder = "Ingrese Metas" } })
                    </div>
                </div>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group has-feedback">
                <label class="col-md-3 control-label ">Logros</label>
                <div class="col-md-8">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-arrow-circle-up"></i></span>
                        @Html.EditorFor(model => model.Logros, new { htmlAttributes = new { id = "logros", @required = "required", type = "text", minlength = 6, @class = "form-control1", @placeholder = "Ingrese logros" } })
                    </div>
                </div>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group has-feedback">
                <label class="col-md-3 control-label ">Dominio</label>
                <div class="col-md-8">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-th-list"></i></span>
                        @Html.DropDownListFor(model => model.Codigo_Seccion, (SelectList)ViewBag.Sections, "Seleccione Dominio", new { id = "codSec", @disabled = "disabled", @required = "required", type = "text", @class = "form-control1" })
                    </div>
                </div>
            </div>

            <div class="panel-footer">
                <div class="form-group">
                    <label class="col-md-3 control-label"></label>
                    <div class="col-md-8">
                        <button type="button" class="btn btn-success btn-sm" id="backToList" onclick="location.href='@Url.Action("Index", "Home")'">Volver al Menú</button>
                    </div>
                </div>
            </div>
        </form>

        <!-- Modal -->
        <div class="modal fade" id="modalNotas" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header" style="padding-bottom:1px">
                        <h3 class="modal-title" id="myModalLabel">Ingreso de Notas Auto Evaluación</h3>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="false">&times;</span></button>
                    </div>
                    <div class="modal-body" style="padding-top:1px">
                        @using (Html.BeginForm("Create", "AutoEvaluationQuestion", FormMethod.Post, new { id = "myForm", encType = "multipart/form-data", @class = "form-group" }))
                        {
                            <div class="agile-tables" style="padding:0px">
                                <div class="-table-info">
                                    <table id="table">
                                        <thead>
                                            <tr>
                                                <th> @Html.DisplayName("Numero Pregunta")</th>
                                                <th> @Html.DisplayName("Texto")</th>
                                                <th> @Html.DisplayName("Nota")</th>
                                            </tr>
                                        </thead>
                                        <tbody id="preguntas">
                                        </tbody>
                                    </table>
                                    <div class="container">
                                        <div id="loading" class="text-center" style="display:none">
                                            <img src="~/Content/ajax-loader.gif" />
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-success btn-sm" data-dismiss="modal">Cancelar</button>
                                        <button type="button" class="btn btn-default btn-sm" id="btn">Aceptar</button>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>


    <script src="~/js/Utiles.js"></script>
</body>
</html>